# vim:ft=kitty
## name: Aurora X
## license: MIT
## based on: Aurora X VS Code theme

background            #07090F
foreground            #A8BEFF
selection_background  #262E47
selection_foreground  #C7D5FF
url_color             #86A5FF
cursor                #86A5FF
cursor_text_color     #07090F

# Tabs
active_tab_background    #86A5FF
active_tab_foreground    #07090F
inactive_tab_background  #15182B
inactive_tab_foreground  #576daf
tab_bar_background       #07090F

# Windows
active_border_color    #86A5FF
inactive_border_color  #15182B

# normal
color0  #07090F
color1  #dd5074
color2  #C3E88D
color3  #FFCB6B
color4  #82AAFF
color5  #C792EA
color6  #89DDFF
color7  #A8BEFF

# bright
color8   #576daf
color9   #FF5370
color10  #64d389
color11  #FFCB6B
color12  #86A5FF
color13  #c778db
color14  #89DDFF
color15  #C7D5FF

# extended colors
color16  #F78C6C
color17  #f07178
