set -g mode-keys vi
set -g status-keys vi

set-option -g status-left-length 50
set-option -g status-right-length 30
set-option -g status-justify centre
set -wg mode-style bg='#FFFFFF',fg='#000000'
set-option -g status-style bg='#000000',fg='#FFFFFF'
set-option -g status-left "#[fg=color2,bold][#{session_name}] #[fg=color255,bold]: #[fg=magenta]#(whoami) "
set -g pane-active-border-style fg='#01FDB0'
set -g pane-border-style fg='#FFFFFF'
set -g message-style bg='#000000',fg='#FFFFFF'
setw -g window-status-bell-style bg='#000000',fg='#FFFFFF'
setw -g window-status-style bg='#000000',fg='#FFFFFF'
setw -g window-status-current-format ' #[fg=red,bold][#[fg=color255]#I:#W#[fg=red]] '
setw -g window-status-format '#[fg=color8][#[fg=color255]#I:#W#[fg=color8]]'

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
